server:
    port: 8080
spring:
    profiles: localhost
    application:
        name: wolf
    datasource:
        url: jdbc:mysql://soubandevextranet.mysql.rds.aliyuncs.com:3306/souban_wolf
        username: souban_wolf
        password: Whalefin403
        driverClassName: com.mysql.jdbc.Driver
        validationQuery: SELECT 1
        testOnBorrow: true
mybatis:
    mapperLocations: mapper/*.xml
    typeAliasesPackage: com.souban.wolf.model
    configuration:
        mapUnderscoreToCamelCase: true
logging:
    level:
       com.ibatis:DEBUG
