server:
    port: 8080
spring:
    profiles: localhost
    application:
        name: wolf
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
        validationQuery: SELECT 1
        testOnBorrow: true
mybatis:
    mapperLocations: mapper/*.xml
    typeAliasesPackage: com.souban.wolf.model
    configuration:
        mapUnderscoreToCamelCase: true
logging:
    level:
       com.ibatis:DEBUG
